#!/usr/bin/env bash

[[ -v RUNNER_DEBUG && "$RUNNER_DEBUG" == 1 ]] && set -x
[[ -o xtrace ]] && export RUNNER_DEBUG=1

set -eu
set -o pipefail

function renameFile() {
  [[ -v RUNNER_DEBUG && "$RUNNER_DEBUG" == 1 ]] && set -x
  [[ -o xtrace ]] && export RUNNER_DEBUG=1

  local splitFile="${1?}"
  local dir="${2?}"
  local kind
  kind="$(yq -r '.kind' "$splitFile")"
  if [[ "$kind" == "" ]]; then
    # skip empty documents
    rm -f "$splitFile"
    return 0
  fi
  local namespace
  namespace="$(yq -r '.metadata.namespace' "$splitFile")"
  local name
  name="$(yq -r '.metadata.name' "$splitFile")"

  local resourceName
  resourceName="$dir/$namespace/$kind/$name.yaml"
  if [[ -f "$resourceName" ]]; then
    echo "'$resourceName' shouldn't already exist" >&2
    return 1
  fi
  mkdir -p "$(dirname "$resourceName")"
  mv "$splitFile" "$resourceName"
}
export -f renameFile

function splitHelmReleaseIntoDir() {
  [[ -v RUNNER_DEBUG && "$RUNNER_DEBUG" == 1 ]] && set -x
  [[ -o xtrace ]] && export RUNNER_DEBUG=1

  local helmrelease="${1?}"
  local helmreleaseDir
  helmreleaseDir="$(dirname "$helmrelease")/$(basename -s .yaml "$helmrelease")"
  if ! [[ -d "$helmreleaseDir" ]]; then
    local yaml="${2?}"
    "$BIN_DIR/templateHelmRelease" -1 <<<"$(sed -s '$a---' <(yq -s -y '.[] | select(.apiVersion | contains("source.toolkit.fluxcd.io"))' <"$yaml") "$helmrelease")" >"${helmrelease}_templated"
    splitYamlIntoDir "${helmrelease}_templated" "$helmreleaseDir"
    rm "${helmrelease}_templated"
  fi
}
export -f splitHelmReleaseIntoDir

function splitYamlIntoDir() {
  [[ -v RUNNER_DEBUG && "$RUNNER_DEBUG" == 1 ]] && set -x
  [[ -o xtrace ]] && export RUNNER_DEBUG=1

  local yaml="${1?}"
  local yamlDir
  yamlDir="$(dirname "$yaml")"
  local dir="${2?}"
  local IFS=$'\n'
  local rc=0
  local splitFile
  local splitPrefix
  splitPrefix="$(basename "$yaml")-"
  local helmrelease

  env -C "$yamlDir" csplit --prefix="$splitPrefix" --suppress-matched "$yaml" '/^---$/' '{*}' >/dev/null || rc="$?"
  if [[ "$rc" != "0" && "$rc" != "1" ]]; then
    return "$rc"
  fi

  find "$yamlDir" -type f -name "${splitPrefix}*" -print0 | parallel -0 renameFile {} "$dir"

  find "$dir" -type d -name HelmRelease -exec find {} -maxdepth 1 -type f -name '*.yaml' -print0 \; | parallel -0 splitHelmReleaseIntoDir {} "$yaml"
}
export -f splitYamlIntoDir

BIN_DIR="$(dirname "$0")" splitYamlIntoDir "$@"
