apiVersion: v2
name: oci-registry
description: An implementation of the OCI Registry spec with filesystem and S3 storage
  back-ends, acting as a pull-through cache (mirror); pushing is not yet implemented
type: application
version: 0.4.5
appVersion: 0.4.5
maintainers:
  - name: cwrau
    email: cwr@teuto.net
  - name: marvinWolff
    email: mw@teuto.net
  - name: tasches
    email: st@teuto.net
dependencies:
  - name: common
    version: 2.2.0
    repository: oci://ghcr.io/teutonet/teutonet-helm-charts
annotations:
  artifacthub.io/images: '- image: docker.io/mcronce/oci-registry:v0.4.5  #  default/Deployment/oci-registry.yaml'
