{{- define "t8s-cluster.clusterClass.apiServer.authenticationConfig" -}}
  {{- $_ := mustMerge . (pick .context "Values") -}}
apiVersion: apiserver.config.k8s.io/v1beta1
kind: AuthenticationConfiguration
jwt:
  {{- range $issuerUrl, $provider := .Values.oidcProviders }}
  - issuer:
      url: {{ $issuerUrl }}
      {{- with $provider.certificateAuthority }}
      certificateAuthority: {{ . | quote }}
      {{- end }}
      audiences: {{- toYaml $provider.audiences | nindent 8 }}
    claimMappings:
      username:
        expression: {{ $provider.claimMappings.username | quote }}
      {{- with $provider.claimMappings.groups }}
      groups:
        expression: {{ . | quote }}
      {{- end }}
    {{- with $provider.claimValidationRules }}
    claimValidationRules: {{- toYaml . | nindent 6 }}
    {{- end }}
  {{- end }}
{{- end -}}
