apiVersion: v2
name: teuto-cnpg
description: >-
  This chart provides a way to create [Cloudnative-PG Helm chart](https://github.com/cloudnative-pg/charts) resources. It abstracts the configuration to be more streamlined and provides a nicer way
  to manage users.

maintainers:
  - email: cwr@teuto.net
    name: cwrau
  - email: mw@teuto.net
    name: marvinWolff
  - email: st@teuto.net
    name: tasches
type: application
version: 3.1.0
dependencies:
  - name: common
    repository: oci://ghcr.io/teutonet/teutonet-helm-charts
    version: 1.8.0
sources:
  - https://github.com/teutonet/teutonet-helm-charts/tree/teuto-cnpg-v3.1.0/charts/teuto-cnpg
  - https://github.com/teutonet/teutonet-helm-charts/tree/main/charts/teuto-cnpg
annotations:
  artifacthub.io/images: |-
    []
