databaseImage:
  registry: ghcr.io
  repository: cloudnative-pg/postgresql
  tag: "18.1@sha256:dba61fa23ee9c52dc2e34170c45ed4ccf47e465dc66847636b1eae724b5ca947"
instances: 3
logLevel: info
storageSize: 1Gi
podMonitorLabels:
  managed.by/monitoring: teutonet
