{{- if eq (include "t8s-cluster.cni" .) "cilium" }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ printf "%s-cni" .Release.Name }}
  namespace: {{ .Release.Namespace}}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  chart:
    spec: {{- include "common.helm.chartSpec" (dict "repo" "cilium" "repoNamespace" "flux-system" "chart" "cilium" "context" $) | nindent 6 }}
  interval: 1h
  driftDetection:
    mode: enabled
  kubeConfig:
    secretRef:
      name: {{ .Release.Name }}-kubeconfig
  healthCheckExprs:
    - apiVersion: apps/v1
      kind: DaemonSet
      current: status.numberAvailable == status.desiredNumberScheduled
      inProgress: status.numberAvailable < status.desiredNumberScheduled
    - apiVersion: apps/v1
      kind: Deployment
      # ignore deployments other than cilium-operator, as they are not critical
      current: metadata.name != "cilium-operator" || (has(status.conditions) && status.conditions.exists(c, c.type == "Available" && c.status == "True"))
      inProgress: metadata.name == "cilium-operator" && (!has(status.conditions) || !status.conditions.exists(c, c.type == "Available" && c.status == "True"))
  install:
    remediation:
      retries: -1
  uninstall:
    disableWait: true
  upgrade:
    timeout: 5m
  storageNamespace: kube-system
  targetNamespace: kube-system
  releaseName: cni
  values:
    nodePort:
      enabled: true
    {{- if .Values.controlPlane.hosted }}
    bpf:
      masquerade: true
      tproxy: true
      enableTCX: true
    endpointRoutes:
      enabled: true
    bandwidthManager:
      enabled: true
    egressGateway:
      enabled: true
    # currently not really possible with kubeadmcontrolplane, as they don't support disabling the built-in kube-proxy
    kubeProxyReplacement: true
    ipam:
      mode: kubernetes
    routingMode: native
    autoDirectNodeRoutes: true
    directRoutingSkipUnreachable: true
    localRedirectPolicies:
      enabled: true
    k8s:
      requireIPv4PodCIDR: true
      {{- $gateway := lookup "gateway.networking.k8s.io/v1" "Gateway" "capi-hosted-control-plane-system" "controlplane" -}}
      {{- if not $gateway -}}
        {{- fail "Hosted control plane Gateway 'controlplane' in namespace 'capi-hosted-control-plane-system' not found" -}}
      {{- else }}
    k8sServiceHost: {{ printf "%s.%s.%s" .Release.Name .Release.Namespace (replace "*." "" (index $gateway.spec.listeners 0).hostname) }}
      {{- end }}
    k8sServicePort: 443
    ipv4NativeRoutingCIDR: 10.0.0.0/16 # default net, see hosted control plane controller
    {{- end }}

    policyDenyResponse: icmp

    rollOutCiliumPods: true
    encryption:
      enabled: false
      nodeEncryption: false
    envoy:
      prometheus:
        enabled: true
    hubble:
      metrics:
        enabled:
          - dns
          - drop
          - tcp
          - flow
          - icmp
          - http
      relay:
        rollOutPods: true
        enabled: true
        prometheus:
          enabled: true
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 65532
          runAsGroup: 65532
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
      ui:
        rollOutPods: true
        enabled: true
        backend:
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          livenessProbe:
            enabled: true
          readinessProbe:
            enabled: true
          resources:
            requests:
              cpu: 10m
              memory: 64Mi
            limits:
              memory: 128Mi
        frontend:
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              memory: 32Mi
          extraVolumes:
            - name: nginx-cache
              emptyDir: {}
            - name: nginx-run
              emptyDir: {}
          extraVolumeMounts:
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
      export:
        static:
          enabled: true
          filePath: stdout
          allowList:
            - '{"verdict":["DROPPED","ERROR"]}'
    operator:
      rollOutPods: true
      prometheus:
        enabled: true
    {{- if .Values.controlPlane.hosted }}
      tolerations:
        - key: node.cluster.x-k8s.io/uninitialized
          effect: NoSchedule
        - key: node.cloudprovider.kubernetes.io/uninitialized
          effect: NoSchedule
          value: "true"
        - key: node.kubernetes.io/not-ready
          effect: NoSchedule
    {{- end }}
    prometheus:
      enabled: true
{{- end }}
