{{- $config := dict -}}
{{- if kindIs "string" .Values.databases -}}
  {{- $config = .Values.databases | fromYaml -}}
{{- else -}}
  {{- $config = .Values.databases -}}
{{- end -}}

{{- $globalExtensions := .Values.globalExtensions | default list -}}

{{- range $name, $db := $config -}}
  {{- $owner := "" -}}
  {{- $dbExtensions := list -}}
  {{- $dbSchemas := list -}}

  {{- if kindIs "string" $db -}}
    {{- $owner = $db -}}
  {{- else -}}
    {{- $owner = $db.owner -}}
    {{- $dbExtensions = $db.extensions | default list -}}
    {{- $dbSchemas = $db.schemas | default list -}}
  {{- end -}}

  {{- $mergedExtensions := concat $dbExtensions $globalExtensions -}}

apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: {{ printf "%s-%s" $.Release.Name ($name | sha1sum | trunc 16) }}
  namespace: {{ $.Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  name: {{ $name | quote }}
  owner: {{ $owner | quote }}
  cluster:
    name: {{ $.Release.Name | quote }}
  {{- if $dbSchemas }}
  schemas:
    {{- range $schem := $dbSchemas }}
    - name: {{ $schem.name | quote }}
      owner: {{ $schem.owner | quote }}
    {{- end }}
    {{- end }}
  {{- if $mergedExtensions }}
  extensions:
    {{- range $ext := $mergedExtensions }}
    {{- if kindIs "string" $ext }}
    - name: {{ $ext | quote }}
    {{- else }}
    - name: {{ $ext.name | quote }}
      {{- if $ext.version }}
      version: {{ $ext.version | quote }}
      {{- end }}
      {{- if $ext.schema }}
      schema: {{ $ext.schema | quote }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- end }}
---
{{ end }}
