apiVersion: v2
dependencies:
  - name: common
    repository: oci://ghcr.io/teutonet/teutonet-helm-charts
    version: 2.2.0
description: t8s-operator cluster with necessary addons
home: https://teuto.net
icon: https://teuto.net/favicon.ico
maintainers:
  - email: cwr@teuto.net
    name: cwrau
  - email: mw@teuto.net
    name: marvinWolff
  - email: st@teuto.net
    name: tasches
name: t8s-cluster
sources:
  - https://github.com/teutonet/teutonet-helm-charts/tree/t8s-cluster-v9.13.0/charts/t8s-cluster
  - https://github.com/teutonet/teutonet-helm-charts/tree/main/charts/t8s-cluster
type: application
version: 9.13.0
annotations:
  artifacthub.io/images: |-
    - image: nvcr.io/nvidia/gpu-operator:v24.9.2                                                                   #  default/HelmRelease/t8s-cluster-gpu-operator/kube-system/Job/gpu-operator-upgrade-crd.yaml
    - image: nvcr.io/nvidia/gpu-operator:v24.9.2                                                                   #  default/HelmRelease/t8s-cluster-gpu-operator/null/Deployment/gpu-operator.yaml
    - image: registry.k8s.io/autoscaling/cluster-autoscaler:v1.35.0                                                #  default/HelmRelease/t8s-cluster-autoscaler/default/Deployment/as-t8s-cluster-autoscaler.yaml
    - image: registry.k8s.io/etcd:3.7.1-0@sha256:a9983dd6d9283138ab926daa307c6c25623636703ecf5645d5df4d666ce9eba2  #  default/ResourceSet/t8s-cluster-etcd-defrag.yaml
    - image: registry.k8s.io/nfd/node-feature-discovery:v0.16.6                                                    #  default/HelmRelease/t8s-cluster-gpu-operator/kube-system/DaemonSet/gpu-operator-node-feature-discovery-worker.yaml
    - image: registry.k8s.io/nfd/node-feature-discovery:v0.16.6                                                    #  default/HelmRelease/t8s-cluster-gpu-operator/kube-system/Deployment/gpu-operator-node-feature-discovery-gc.yaml
    - image: registry.k8s.io/nfd/node-feature-discovery:v0.16.6                                                    #  default/HelmRelease/t8s-cluster-gpu-operator/kube-system/Deployment/gpu-operator-node-feature-discovery-master.yaml
    - image: registry.k8s.io/nfd/node-feature-discovery:v0.16.6                                                    #  default/HelmRelease/t8s-cluster-gpu-operator/kube-system/Job/gpu-operator-node-feature-discovery-prune.yaml
    - image: registry.k8s.io/provider-os/cinder-csi-plugin:v1.36.0                                                 #  default/HelmRelease/t8s-cluster-csi/kube-system/DaemonSet/openstack-cinder-csi-nodeplugin.yaml
    - image: registry.k8s.io/provider-os/cinder-csi-plugin:v1.36.0                                                 #  default/HelmRelease/t8s-cluster-csi/kube-system/Deployment/openstack-cinder-csi-controllerplugin.yaml
    - image: registry.k8s.io/provider-os/openstack-cloud-controller-manager:v1.36.0                                #  default/HelmRelease/t8s-cluster-ccm/kube-system/DaemonSet/openstack-cloud-controller-manager.yaml
    - image: registry.k8s.io/sig-storage/csi-attacher:v4.10.0                                                      #  default/HelmRelease/t8s-cluster-csi/kube-system/Deployment/openstack-cinder-csi-controllerplugin.yaml
    - image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.15.0                                         #  default/HelmRelease/t8s-cluster-csi/kube-system/DaemonSet/openstack-cinder-csi-nodeplugin.yaml
    - image: registry.k8s.io/sig-storage/csi-provisioner:v5.3.0                                                    #  default/HelmRelease/t8s-cluster-csi/kube-system/Deployment/openstack-cinder-csi-controllerplugin.yaml
    - image: registry.k8s.io/sig-storage/csi-resizer:v1.14.0                                                       #  default/HelmRelease/t8s-cluster-csi/kube-system/Deployment/openstack-cinder-csi-controllerplugin.yaml
    - image: registry.k8s.io/sig-storage/csi-snapshotter:v8.4.0                                                    #  default/HelmRelease/t8s-cluster-csi/kube-system/Deployment/openstack-cinder-csi-controllerplugin.yaml
    - image: registry.k8s.io/sig-storage/livenessprobe:v2.17.0                                                     #  default/HelmRelease/t8s-cluster-csi/kube-system/DaemonSet/openstack-cinder-csi-nodeplugin.yaml
    - image: registry.k8s.io/sig-storage/livenessprobe:v2.17.0                                                     #  default/HelmRelease/t8s-cluster-csi/kube-system/Deployment/openstack-cinder-csi-controllerplugin.yaml
