global:
  # it's important that the `url` is the first key and `charts` is right below, otherwise renovate won't detect it
  helmRepositories:
    cilium:
      url: oci://quay.io/cilium/charts
      charts:
        cilium: 1.20.1
      condition: '{{ eq (include "t8s-cluster.cni" .) "cilium" }}'
    nvidia:
      url: https://helm.ngc.nvidia.com/nvidia
      charts:
        gpu-operator: 24.9.2
      condition: '{{ include "t8s-cluster.hasGPUNodes" (dict "context" $) }}'
    cloud-provider-openstack:
      url: https://kubernetes.github.io/cloud-provider-openstack
      charts:
        openstack-cloud-controller-manager: 2.36.3
        openstack-cloud-controller-manager 2.34.x: 2.34.2
        openstack-cloud-controller-manager 2.33.x: 2.33.1
        openstack-cloud-controller-manager 2.32.x: 2.32.1
        openstack-cloud-controller-manager 2.31.x: 2.31.5
        openstack-cinder-csi: 2.36.3
        openstack-cinder-csi 2.34.x: 2.34.3
        openstack-cinder-csi 2.33.x: 2.33.1
        openstack-cinder-csi 2.32.x: 2.32.2
        openstack-cinder-csi 2.31.x: 2.31.8
    autoscaler:
      url: https://kubernetes.github.io/autoscaler
      charts:
        cluster-autoscaler: 9.59.0
    cetic:
      url: https://cetic.github.io/helm-charts
  busybox:
    image:
      registry: docker.io
      repository: busybox
      tag: 1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616
  etcd:
    image:
      registry: registry.k8s.io
      repository: etcd
      tag: 3.7.1-0@sha256:a9983dd6d9283138ab926daa307c6c25623636703ecf5645d5df4d666ce9eba2
  jq:
    image:
      registry: ghcr.io
      repository: jqlang/jq
      tag: 1.8.1@sha256:4f34c6d23f4b1372ac789752cc955dc67c2ae177eb1b5860b75cdc5091ce6f91
  kubectl:
    image:
      registry: registry.k8s.io
      repository: kubectl
      tag: 1.33.4@sha256:261a9ed843eb68e3d50da132245e2221d75ca19504130e47bd32788c0ff339a0
  s3:
    image:
      registry: docker.io
      repository: minio/mc
      tag: RELEASE.2024-11-21T17-21-54Z@sha256:771f5ad7925a6b5e069786d8e847a292de320f1e3e3203647e29f47ec9b3d93b
  injectedCertificateAuthorities: ""
  kubeletExtraConfig:
    # This is only used when using 1.27 or later
    maxParallelImagePulls: 4

metadata:
  serviceLevelAgreement: None
  supportProjectUrl: ""
  configGroupUrl: ""
  remarks: ""
  friendlyName: ""

controlPlane:
  hosted: false
  audit: false
  flavor: standard.2.1905
  singleNode: false
  allowedCIDRs: []
  resources:
    requests:
      memory: 2Gi
    limits:
      memory: 4Gi
  etcdBackup: false

oidcProviders:
  https://staff-auth.k8s.teuto.net:
    audiences:
      - kubernetes
    claimMappings:
      username: claims.email
      groups: dyn(claims.groups).map(g, "teuto.net:" + g)
    claimValidationRules:
      - expression: (has(claims.email_verified) && claims.email_verified) || !has(claims.email_verified)
        message: email must be verified
  https://auth.k8s.teuto.net:
    audiences:
      - kubernetes
    claimMappings:
      username: claims.email
      groups: dyn(claims.groups).map(g, "teuto.net:" + g)
    claimValidationRules:
      - expression: (has(claims.email_verified) && claims.email_verified) || !has(claims.email_verified)
        message: email must be verified

quotas: {}

version:
  major: 1
  minor: 25
  patch: 0

nodePools: {}
additionalComputePlaneSecurityGroups: []

bastion:
  enabled: false
  availabilityZone: null
  sshKeyName: null

containerRegistryMirror:
  additionallyMirroredRegistries: []
  mirrorEndpoint: https://mirror.teuto.net

sshKeyName: null

cni: auto

openstackImageNamePrefix: ""
