{{- $enabled := false -}}
{{- range $_, $machineDeploymentClass := .Values.nodePools }}
  {{- $replicas := $machineDeploymentClass.replicas -}}
  {{- $maxReplicas := $machineDeploymentClass.maxReplicas | default $replicas -}}
  {{- if ne $replicas $maxReplicas }}
    {{- $enabled = true -}}
  {{- end }}
{{- end }}
{{- if $enabled -}}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ printf "%s-autoscaler" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  chart:
    spec: {{- include "common.helm.chartSpec" (dict "repo" "autoscaler" "repoNamespace" "flux-system" "chart" "cluster-autoscaler" "context" $) | nindent 6 }}
  interval: 1h
  driftDetection:
    mode: enabled
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: {{ printf "%s-autoscaler-clusterapi-cluster-autoscaler" .Release.Name }}
            patch: |
              - op: add
                path: /spec/template/spec/securityContext
                value:
                  runAsNonRoot: true
                  runAsUser: 65534
                  fsGroup: 65534
                  seccompProfile:
                    type: RuntimeDefault
  values:
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    autoDiscovery:
      clusterName: {{ .Release.Name }}
    cloudProvider: clusterapi
    # workload-management
    clusterAPIMode: kubeconfig-incluster
    clusterAPIKubeconfigSecret: {{ .Release.Name }}-kubeconfig
    extraArgs:
      scale-down-utilization-threshold: 0.8
      skip-nodes-with-local-storage: false
    serviceMonitor:
      enabled: true
      namespace: {{ .Release.Namespace }}
{{- end -}}
