{{- $enabled := false -}}
{{- range $_, $machineDeploymentClass := .Values.nodePools }}
  {{- $replicas := $machineDeploymentClass.replicas -}}
  {{- $maxReplicas := $machineDeploymentClass.maxReplicas | default $replicas -}}
  {{- if ne $replicas $maxReplicas }}
    {{- $enabled = true -}}
  {{- end }}
{{- end }}
{{- if $enabled -}}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ printf "%s-autoscaler" .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
spec:
  chart:
    spec: {{- include "common.helm.chartSpec" (dict "repo" "autoscaler" "repoNamespace" "flux-system" "chart" "cluster-autoscaler" "context" $) | nindent 6 }}
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    fullnameOverride: {{ printf "as-%s-autoscaler" .Release.Name }}
    autoDiscovery:
      clusterName: {{ .Release.Name }}
    cloudProvider: clusterapi
    # workload-management
    clusterAPIMode: kubeconfig-incluster
    clusterAPIKubeconfigSecret: {{ .Release.Name }}-kubeconfig
    extraArgs:
      scale-down-utilization-threshold: 0.8
      skip-nodes-with-local-storage: false
    podDisruptionBudget: false
    serviceMonitor:
      enabled: true
      namespace: {{ .Release.Namespace }}
    rbac:
      # needed until https://github.com/kubernetes/autoscaler/issues/6490#issuecomment-4590829570
      # has been addressed
      clusterScoped: true
      additionalRules:
        - apiGroups:
            - infrastructure.cluster.x-k8s.io
          resources:
            - openstackmachinetemplates
          verbs:
            - get
            - list
            - watch
{{- end -}}
