{{- if and (eq .Values.registry.storage.mode "s3") (not .Values.registry.storage.s3.authSecret.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "oci-registry.s3SecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
type: Opaque
data:
  access_key: {{ required "registry.storage.s3.authSecret.accessKey is required when registry.storage.s3.authSecret.name is not set" .Values.registry.storage.s3.authSecret.accessKey | b64enc | quote }}
  secret_key: {{ required "registry.storage.s3.authSecret.secretKey is required when registry.storage.s3.authSecret.name is not set" .Values.registry.storage.s3.authSecret.secretKey | b64enc | quote }}
{{- end }}
