apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  {{- with .Values.registry.service.annotations }}
  annotations: {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.registry.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector: {{- include "common.labels.matchLabels" $ | nindent 4 }}
