{{- define "base-cluster.prometheus-stack.grafana.ini.ingress" -}}
  {{- $host := printf "https://%s" (include "base-cluster.grafana.host" .context) -}}
server:
  root_url: {{ $host }}
auth:
  signout_redirect_url: {{ $host }}
{{- end -}}

{{- define "base-cluster.prometheus-stack.grafana.ini.oauth" -}}
  {{- $_ := mustMerge . (pick .context "Values") -}}
  {{- with .Values.global.authentication -}}
    {{- $issuerUrl := printf "https://%s%s" .config.issuerHost .config.issuerPath -}}
auth:
  oauth_auto_login: true
  disable_login_form: false
auth.generic_oauth:
  enabled: true
  allow_sign_up: true
  api_url: {{ printf "%s%s" $issuerUrl .grafana.apiPath }}
  auth_url: {{ printf "%s%s" $issuerUrl .grafana.authenticationPath }}
  token_url: {{ printf "%s%s" $issuerUrl .grafana.tokenPath }}
  client_id: {{ .config.clientId }}
  client_secret: ${OIDC_CLIENT_SECRET}
  name: OAuth
  role_attribute_path: {{ .grafana.roleAttributePath | quote }}
  scopes: openid profile email
  use_pkce: true
  {{- end -}}
{{- end -}}

{{- define "base-cluster.prometheus-stack.grafana.config" -}}
enabled: true
securityContext:
  seccompProfile:
    type: RuntimeDefault
containerSecurityContext: {{- include "base-cluster.prometheus-stack.containerSecurityContext" (dict) | nindent 2 }}
resources: {{- include "common.resources" .Values.monitoring.grafana | nindent 2 }}
{{- if .Values.monitoring.grafana.persistence.enabled }}
persistence: {{- include "common.storage.class" (dict "persistence" .Values.monitoring.grafana.persistence "global" $.Values.global) | nindent 2 }}
  enabled: true
  size: {{ .Values.monitoring.grafana.persistence.size }}
  accessModes:
    - ReadWriteOnce
deploymentStrategy:
  type: Recreate
{{- end }}
serviceMonitor:
  interval: "30s"
  labels:
    monitoring/provisioned-by: base-cluster
podAnnotations:
  # This might change on every `template` call, this can be ignored
  checksum/secret: {{ include "common.utils.checksumTemplate" (dict "path" "/monitoring/kube-prometheus-stack/grafana-secret.yaml" "context" $) }}
admin:
  existingSecret: {{ include "common.secrets.name" (dict "defaultNameSuffix" "grafana" "context" $) }}
  userKey: username
  passwordKey: password
plugins:
  {{- with .Values.monitoring.grafana.additionalPlugins }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
defaultDashboardsEnabled: true
imageRenderer:
  enabled: true
  {{- with .Values.global.imageRenderer.image }}
  image:
    registry: {{ $.Values.global.imageRegistry | default .registry }}
    repository: {{ .repository }}
    tag: {{ .tag }}
  {{- end }}
  automountServiceAccountToken: false
  securityContext:
    seccompProfile:
      type: RuntimeDefault
    runAsNonRoot: true
    runAsUser: 472
    runAsGroup: 472
  {{- if .Values.monitoring.grafana.notifiers }}
extraEmptyDirMounts:
  - name: provisioning-notifiers
    mountPath: /etc/grafana/provisioning/notifiers
notifiers:
  notifiers.yaml:
    notifiers: {{- toYaml .Values.monitoring.grafana.notifiers | nindent 6 }}
  {{- end }}
dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: custom
        orgId: 1
        folder: ''
        type: file
        disableDeletion: true
        editable: true
        options:
          path: /var/lib/grafana/dashboards/custom
sidecar:
  dashboards:
    enabled: true
    resource: configmap
    searchNamespace: ALL
  datasources:
    enabled: true
    resource: both
    searchNamespace: ALL
  resources: {{- include "common.resources" .Values.monitoring.grafana.sidecar | nindent 4 }}
  securityContext: {{- include "base-cluster.prometheus-stack.containerSecurityContext" (dict) | nindent 4 }}
dashboards:
  {{- $customDashboards := dict }}
  {{- range $name, $dashboard := .Values.monitoring.grafana.dashboards.custom }}
    {{- $create := true -}}
    {{- if $dashboard.condition -}}
      {{- $create = eq (include "common.tplvalues.render" (dict "value" $dashboard.condition "context" (deepCopy $))) "true" -}}
    {{- end -}}
    {{- if $create }}
      {{- $customDashboards = set $customDashboards $name (omit $dashboard "condition") }}
    {{- end }}
  {{- end }}
  custom: {{- mustMerge (deepCopy .Values.monitoring.grafana.additionalDashboards) $customDashboards | toYaml | nindent 4 }}
{{- include "base-cluster.monitoring.ingress" (dict "name" "grafana" "context" $) | nindent 0 }}
{{- $grafanaIni := .Values.monitoring.grafana.config | default (dict) }}
{{- if and (ne .Values.ingress.provider "none") .Values.monitoring.grafana.ingress.enabled .Values.certManager.email (or .Values.global.baseDomain .Values.monitoring.grafana.ingress.customDomain) }}
  {{- $grafanaIni = mustMerge $grafanaIni (include "base-cluster.prometheus-stack.grafana.ini.ingress" (dict "context" $) | fromYaml) }}
  {{- if .Values.global.authentication.config }}
    {{- $grafanaIni = mustMerge $grafanaIni (include "base-cluster.prometheus-stack.grafana.ini.oauth" (dict "context" $) | fromYaml) }}
envValueFrom:
  OIDC_CLIENT_SECRET:
    secretKeyRef:
      key: client-secret
      name: {{ include "common.secrets.name" (dict "defaultNameSuffix" "oauth-proxy" "context" $) }}
      optional: false
  {{- end }}
{{- end }}
{{- if $grafanaIni }}
grafana.ini: {{- toYaml $grafanaIni | nindent 2 }}
{{- end }}
downloadDashboards:
  securityContext: {{- include "base-cluster.prometheus-stack.containerSecurityContext" (dict) | nindent 4 }}
initChownData:
  enabled: false
{{- end -}}
