{{- define "base-cluster.monitoring.ingress" -}}
  {{- $_ := mustMerge . (pick .context "Values") -}}
  {{- $ingress := include "base-cluster.monitoring.ingress.config" (dict "name" .name "context" .context) | fromYaml -}}
  {{- if include "base-cluster.monitoring.ingress.enabled" (dict "name" .name "context" .context) -}}
    {{- $host := include (printf "base-cluster.%s.host" .name) .context -}}
ingress:
  enabled: true
  {{- if or (not .Values.dns.provider) $ingress.customDomain }}
  annotations:
    kubernetes.io/tls-acme: "true"
  {{- end }}
  hosts:
    - {{ $host }}
  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ include "base-cluster.certificate" (dict "name" .name "customDomain" $ingress.customDomain "context" .context) }}
  {{- end -}}
{{- end -}}

{{- define "base-cluster.prometheus-stack.containerSecurityContext" -}}
capabilities:
  drop:
    - ALL
allowPrivilegeEscalation: false
privileged: false
{{- end -}}

{{- define "base-cluster.alertmanager.ingress" -}}
  {{- toYaml .Values.monitoring.prometheus.alertmanager.ingress -}}
{{- end -}}

{{- define "base-cluster.monitoring.ingress.config" -}}
  {{- $_ := mustMerge . (pick .context "Values") -}}
  {{- $ingress := dig .name "ingress" nil .Values.monitoring -}}
  {{- if not $ingress -}}
    {{- $ingress = include (printf "base-cluster.%s.ingress" .name) .context | fromYaml -}}
  {{- end -}}
  {{- toYaml $ingress -}}
{{- end -}}

{{- define "base-cluster.monitoring.ingress.enabled" -}}
  {{- $_ := mustMerge . (pick .context "Values") -}}
  {{- $ingress := include "base-cluster.monitoring.ingress.config" (dict "name" .name "context" .context) | fromYaml -}}
  {{- $domainIsConfigured := or (not (empty .Values.global.baseDomain)) (not (empty $ingress.customDomain)) -}}
  {{- $certManagerIsConfigured := not (empty .Values.certManager.email) -}}
  {{- $ingressSpecificallyDisabled := eq false $ingress.enabled -}}
  {{- and $certManagerIsConfigured (not $ingressSpecificallyDisabled) (ne .Values.ingress.provider "none") $domainIsConfigured | ternary true "" -}}
{{- end -}}

{{- define "base-cluster.monitoring.unauthenticated-ingress.enabled" -}}
  {{- $_ := mustMerge . (pick .context "Values") -}}
  {{- $ingress := include "base-cluster.monitoring.ingress.config" (dict "name" .name "context" .context) | fromYaml -}}
  {{- if include "base-cluster.monitoring.ingress.enabled" (dict "name" .name "context" .context) -}}
    {{- and (empty .Values.global.authentication.config) (dig "enabled" false $ingress) | ternary true "" -}}
  {{- end -}}
{{- end -}}

{{- define "base-cluster.monitoring.authenticated-ingress.enabled" -}}
  {{- $_ := mustMerge . (pick .context "Values") -}}
  {{- $ingress := include "base-cluster.monitoring.ingress.config" (dict "name" .name "context" .context) | fromYaml -}}
  {{- if include "base-cluster.monitoring.ingress.enabled" (dict "name" .name "context" .context) -}}
    {{- and (not (empty .Values.global.authentication.config)) (dig "enabled" true $ingress) | ternary true "" -}}
  {{- end -}}
{{- end -}}

{{- define "base-cluster.prometheus.controlPlaneComponents" -}}
  {{- $kubeProxy := false -}}
  {{- if typeIs "bool" .Values.monitoring.prometheus.kubeProxy -}}
    {{- $kubeProxy = .Values.monitoring.prometheus.kubeProxy -}}
  {{- else -}}
    {{- $kubeProxy = not (empty (lookup "apps/v1" "DaemonSet" "kube-system" "kube-proxy")) -}}
  {{- end -}}
  {{- $kubeScheduler := false -}}
  {{- $kubeControllerManager := false -}}
  {{- if typeIs "bool" .Values.monitoring.prometheus.kubeScheduler -}}
    {{- $kubeScheduler = .Values.monitoring.prometheus.kubeScheduler -}}
  {{- end -}}
  {{- if typeIs "bool" .Values.monitoring.prometheus.kubeControllerManager -}}
    {{- $kubeControllerManager = .Values.monitoring.prometheus.kubeControllerManager -}}
  {{- end -}}
  {{- if or (not (typeIs "bool" .Values.monitoring.prometheus.kubeScheduler)) (not (typeIs "bool" .Values.monitoring.prometheus.kubeControllerManager)) -}}
    {{- range (dig "items" (list) (lookup "v1" "Pod" "kube-system" "")) -}}
      {{- $component := dig "metadata" "labels" "component" "" . -}}
      {{- if and (eq $component "kube-scheduler") (not (typeIs "bool" $.Values.monitoring.prometheus.kubeScheduler)) -}}
        {{- $kubeScheduler = true -}}
      {{- end -}}
      {{- if and (eq $component "kube-controller-manager") (not (typeIs "bool" $.Values.monitoring.prometheus.kubeControllerManager)) -}}
        {{- $kubeControllerManager = true -}}
      {{- end -}}
    {{- end -}}
  {{- end -}}
{{- dict "kubeProxy" $kubeProxy "kubeScheduler" $kubeScheduler "kubeControllerManager" $kubeControllerManager | toYaml -}}
{{- end -}}
