{{- if .Values.monitoring.prometheus.alertmanager.receivers }}
apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-receiver-credentials
  namespace: monitoring
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: monitoring
type: Opaque
{{- $list := dict -}}
{{- if (.Values.monitoring.deadMansSwitch).pingKey -}}
  {{- $list = set $list "healthchecks.io" (printf "https://hc-ping.com/%s/%s-monitoring" .Values.monitoring.deadMansSwitch.pingKey (include "base-cluster.deadMansSwitch.checkName" .)) -}}
{{- end -}}
{{- $keys := list "botToken" "password" "integrationKey" -}}
{{- range $name, $receiver := .Values.monitoring.prometheus.alertmanager.receivers -}}
  {{- range $key := $keys -}}
    {{- if hasKey $receiver $key -}}
      {{- $value := index $receiver $key -}}
      {{- $splitted := include "base-cluster.monitoring.alertmanager.receiver.splitName" (dict "name" $name) | fromYaml -}}
      {{- $list = set $list $splitted.name $value -}}
    {{- end -}}
  {{- end -}}
{{- end }}
stringData: {{- toYaml $list | nindent 2 }}
{{- end }}
