global:
  clusterName: test
  baseDomain: example.com
  serviceLevelAgreement: None
ingress:
  provider: traefik
  extraPorts:
    mqtt:
      expose:
        default: true
      exposedPort: 1883
      port: 1883
      protocol: TCP
    mqtts:
      expose:
        default: true
      exposedPort: 8883
      port: 8883
      protocol: TCP
      proxyProtocol:
        insecure: true
