flux:
  gitRepositories:
    main:
      url: ssh://user@example.com/repo.git
      decryption:
        provider: sops
kyverno:
  enabled: true
backup:
  provider:
    velero:
      defaultLocation: location
      backupStorageLocations:
        location:
          provider:
            minio:
              url: https://minio.com
              existingSecret:
                name: secret
          prefix: /prefix
          bucket: bucket
        location-direct:
          provider:
            minio:
              url: https://minio.com
              accessKeyID: accessKeyID
              secretAccessKey: secretAccessKey
          bucket: bucket-direct
storage:
  readWriteMany:
    enabled: true
global:
  clusterName: test
  baseDomain: example.com
  serviceLevelAgreement: None
  priorityClasses:
    custom-priority:
      value: 600
      description: a custom priority class
      preemptionPolicy: Never
  namespaces:
    custom-namespace:
      resources:
        defaults:
          requests:
            cpu: 50m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 300Mi
        quotas:
          limits.cpu: "1"
          limits.memory: 1Gi
  authentication:
    config:
      clientId: clientId
      clientSecret: clientSecret
      issuerHost: keycloak.example.com
      issuerPath: /auth/realms/test
    grafana:
      apiPath: /oauth2/userinfo/grafana
      authenticationPath: /oauth2/authorize/grafana
      tokenPath: /oauth2/token/grafana
      roleAttributePath: "contains(groups, 'admin') && 'Admin' || 'Viewer'"
certManager:
  email: admin@example.com
monitoring:
  grafana:
    adminPassword: test
  tracing:
    enabled: true
  deadMansSwitch:
    pingKey: PING_KEY
    apiKey: API_KEY
  prometheus:
    enabled: true
    alertmanager:
      defaultReceiver: testmail
      receivers:
        pagerduty:
          integrationKey: INTEGRATION_KEY__INTEGRATION_KEY
        email testmail:
          from: test2@mail.com
          to: test2@mail.com
          host: smtp.mail.com
          port: 587
          username: root
          password: abcd
          sendResolved: false
        telegram:
          botToken: botToken
          chatid: 123456789
      routes:
        - matchers:
            - namespace=~"test"
          receiver: pagerduty
    blackboxExporter:
      enabled: true
  loki:
    enabled: true
  metricsServer:
    enabled: true
  securityScanning:
    enabled: true
ttl-controller:
  enabled: true
descheduler:
  enabled: true
ingress:
  provider: nginx
reflector:
  enabled: true
dns:
  provider:
    cloudflare:
      apiToken: API_TOKEN
