flux:
  gitRepositories:
    main:
      url: ssh://user@example.com/repo.git
      decryption:
        provider: sops
kyverno:
  enabled: true
backup:
  provider:
    velero:
      defaultLocation: location
      backupStorageLocations:
        location:
          provider:
            minio:
              url: https://minio.com
              existingSecret:
                name: secret
          prefix: /prefix
          bucket: bucket
storage:
  readWriteMany:
    enabled: true
global:
  baseDomain: example.com
monitoring:
  tracing:
    enabled: true
  deadMansSwitch:
    pingKey: PING_KEY
    apiKey: API_KEY
  prometheus:
    enabled: true
    alertmanager:
      receivers:
        pagerduty:
          integrationKey: INTEGRATION_KEY__INTEGRATION_KEY
  loki:
    enabled: true
  metricsServer:
    enabled: true
  securityScanning:
    enabled: true
ttl-controller:
  enabled: true
descheduler:
  enabled: true
ingress:
  provider: nginx
reflector:
  enabled: true
dns:
  provider:
    cloudflare:
      apiToken: API_TOKEN
