global:
  namespaces:
    dev: {}
flux:
  gitRepositories:
    main:
      url: ssh://git@myfancygit.com/group/name.git
certManager:
  email: null
rbac:
  roles:
    admin:
      - apiGroups:
          - '*'
        resources:
          - '*'
        verbs:
          - '*'
      - nonResourceURLs:
          - '*'
        verbs:
          - '*'
  accounts:
    dev1:
      roles:
        admin:
          - dev
