apiVersion: v2
appVersion: 2.0.0
dependencies:
  - name: common
    repository: oci://ghcr.io/teutonet/teutonet-helm-charts
    version: 1.2.1
description: A Helm chart for deploying the portal worker application to k8s
maintainers:
  - email: cwr@teuto.net
    name: cwrau
  - email: mw@teuto.net
    name: marvinWolff
  - email: st@teuto.net
    name: tasches
name: teuto-portal-k8s-worker
sources:
  - https://github.com/teutonet/teutonet-helm-charts/tree/teuto-portal-k8s-worker-v3.1.2/charts/teuto-portal-k8s-worker
  - https://github.com/teutonet/teutonet-helm-charts/tree/main/charts/teuto-portal-k8s-worker
type: application
version: 3.1.2
annotations:
  artifacthub.io/images: |
    - image: registry-gitlab.teuto.net/4teuto/dev/teuto-portal/teuto-portal-k8s-worker/teuto-portal-k8s-worker:3.3.0  #  default/Deployment/teuto-portal-k8s-worker.yaml
