global:
  imagePullSecrets: []
  networkPolicy:
    dnsLabels:
      io.kubernetes.pod.namespace: kube-system
      k8s-app: kube-dns
  podSecurityContext:
    runAsNonRoot: true
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    privileged: false
    capabilities:
      drop:
        - ALL
    runAsGroup: 1000
    runAsUser: 1000

  securityContext:
    fsGroup: 1000
    runAsUser: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    fsGroupChangePolicy: OnRootMismatch

worker:
  config:
    loggingFormat: json
  image:
    registry: registry-gitlab.teuto.net
    repository: 4teuto/dev/teuto-portal/teuto-portal-k8s-worker/teuto-portal-k8s-worker
    tag: 4.5.0@sha256:1d55b78f0fed29083d7a6e354392c996beb23e460dc79052666b6545eb42d082
  database:
    credentials:
      secret:
        name: ""
    host: localhost
    port: 5432
  kubeconfig:
    secret:
      name: ""
  resourcesPreset: micro
  resources:
    limits:
      memory: 1Gi
