{{- if .Capabilities.APIVersions.Has "storagemigration.k8s.io/v1beta1/StorageVersionMigration" }}
{{- range $crd := (lookup "apiextensions.k8s.io/v1" "CustomResourceDefinition" "" "").items | default list }}
---
apiVersion: storagemigration.k8s.io/v1beta1
kind: StorageVersionMigration
metadata:
  name: {{ $crd.metadata.name }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
spec:
  resource:
    group: {{ $crd.spec.group }}
    resource: {{ $crd.spec.names.plural }}
{{- end }}
{{- end }}
