name: Check license links

on:
  workflow_call: {}

jobs:
  check-license-links:
    name: check license links
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          repository: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.repo.full_name || github.repository }}
          ref: ${{ github.event_name == 'pull_request_target' && github.event.pull_request.head.sha || github.sha }}
          persist-credentials: false
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          path: scripts # needed because otherwise tokens could be stolen
          sparse-checkout: |
            .github
          sparse-checkout-cone-mode: false
          persist-credentials: false
      - run: pip install yq
      - run: gem install licensee --no-document --version 10.0.0
      - run: ./scripts/.github/scripts/check-license-links.sh
