name: Wait for checks
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  wait-for-checks:
    runs-on: ubuntu-latest
    permissions:
      checks: read
    steps:
      - env:
          GH_TOKEN: ${{ github.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
          IGNORED_JOBS: generateDiffCommentBody,postDiffComment
          CURRENT_JOB: ${{ github.job }}
        timeout-minutes: 60
        run: |
          [[ "$RUNNER_DEBUG" == 1 ]] && set -x
          set -e
          set -o pipefail

          until unfinished_jobs="$(gh pr checks "${PR_URL}" --json name,state | jq --arg ignored "$IGNORED_JOBS,$CURRENT_JOB" -e 'map(select(([.state] | inside(["SUCCESS", "SKIPPED"]) | not) and ([.name] | inside($ignored | split(",")) | not))) | (map("\(.name) (\(.state))") | join(", ") | stderr) | length == 0' 2>&1 >/dev/null)"; do
            echo "The jobs '$unfinished_jobs' are not (successfully) finished yet" >&2
            sleep 5
          done
